apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000 # Adjust to your app's internal port if different
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: amitfreeze/oct_user_service:latest
          envFrom:
            - configMapRef:
                name: ecomm-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecomm-secret
                  key: mysql-app-password
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: amitfreeze/oct_product_service:latest
          envFrom:
            - configMapRef:
                name: ecomm-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecomm-secret
                  key: mysql-app-password
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: amitfreeze/oct_order_service:latest
          envFrom:
            - configMapRef:
                name: ecomm-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecomm-secret
                  key: mysql-app-password