apiVersion: v1
kind: Secret
metadata:
  name: ecomm-secret
type: Opaque
stringData:
  mysql-root-password: "rootpassword"
  mysql-app-password: "apppassword"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecomm-config
data:
  DB_HOST: "db"
  DB_USER: "appuser"
  DB_NAME: "app_db"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
data:
  init.sql: |
    -- USER SERVICE DATABASE AND TABLES
    USE app_db;
    CREATE TABLE users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(50), email VARCHAR(50) UNIQUE, password VARCHAR(100)
    );
    INSERT INTO users (name, email, password) VALUES ('Alice', 'alice@example.com', 'password123');

    -- PRODUCT SERVICE TABLES

    CREATE TABLE products (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(50), price DECIMAL(10,2), stock INT
    );
    INSERT INTO products (name, price, stock) VALUES ('Laptop', 999.99, 10), ('Wireless Mouse', 25.50, 50);

    -- ORDER SERVICE DATABASE AND TABLES

    CREATE TABLE orders (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT, product_id INT, product_name VARCHAR(50), total_price DECIMAL(10,2),
        order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi